### ISSUE TITLE
Website not under my account

### ISSUE THREAD

**Issue by kingclubs** [joomla/showcase.joomla.org#11]
Hello,

I added a second site to the showcase and when I click on "My Sites" it is there and has been approved but my other site is not in my list of sites? How do I add it to my account?

Here are my sites when I click on my name:
https://showcase.joomla.org/browse-sites.html?search=showcase_search&task=search&item_creator=Effective%20Designs

Here is the site that I'd like to make some changes too but I cant access from my account:
https://showcase.joomla.org/browse-sites/16606.html

**Comment by conconnl** [comment]
@sebastienlapoux can you please help this user?

**Comment by sebastienlapoux** [comment]
Hi @kingclubs ,

"Pacific Shores Medical Group" site has been submitted by Mike Kritzer and "Organized Labor" by another user (but no more active and so deleted).

Can we assign the site "Organized Labor" to Mike Kritzer account?

Thanks.

**Comment by kingclubs** [comment]
Yes please. I’ll be adding more soon.

Thank you. :)

---
Mike Kritzer
Web Developer
mike@effectivedesigns.com
Portfolio: http://www.MikeKritzer.com/

**Comment by sebastienlapoux** [comment]
Done! Thanks to close if ok for you.
Regards.
