### ISSUE TITLE
User icon is not aligned properly

### ISSUE THREAD

**Issue by Raunaksingh100** [joomla/showcase.joomla.org#14]
### description-
The users icon is not aligned in mobile view see in the screenshot for given below for the better understanding.

### screenshot-
![now](https://user-images.githubusercontent.com/65535360/103543165-10f54c80-4ec4-11eb-8ebf-71ffa6909208.PNG)

**Comment by sebastienlapoux** [comment]
Thank you!

Of course it depends of your advice width.

![IMG_5836](https://user-images.githubusercontent.com/13470265/103544448-6881c100-4ea0-11eb-8e54-6150c6f0471a.PNG)

The Galaxy fold screen is very small if you use only one screen.
Very few case, we will discuss and decide with the team if it needs to be fixed.

Thanks.

**Comment by KalpitRathod** [comment]
> Thank you!
> 
> Of course it depends of your advice width.
> 
> ![IMG_5836](https://user-images.githubusercontent.com/13470265/103544448-6881c100-4ea0-11eb-8e54-6150c6f0471a.PNG)
> 
> The Galaxy fold screen is very small if you use only one screen.
> Very few case, we will discuss and decide with the team if it needs to be fixed.
> 
> Thanks.

hey how to do that thing after fork and download the project

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by sebastienlapoux** [comment]
Part of the common template used by joomla.org websites. New version to come. Closing this issue.
