### ISSUE TITLE
too much blank lines in case study page

### ISSUE THREAD

**Issue by vinayaks0031** [joomla/showcase.joomla.org#15]
On
![283564](https://user-images.githubusercontent.com/76878117/104011470-29bb7600-51d4-11eb-911e-8e51ddcf86d3.jpg)
 case studies page it is showing too much blank lines between the "Case studies" and dropdown box, In pc it is okay but in phone its look odd fix that then it will looks good

**Comment by KalpitRathod** [comment]
i am working on this issue

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by sebastienlapoux** [comment]
Fixed by the showcase team.
Thank you.
