### ISSUE TITLE
[Implement] - Implement Captcha

### ISSUE THREAD

**Issue by conconnl** [joomla/showcase.joomla.org#2]
Please implement "CAPTCHA - Invisible reCAPTCHA" and make sure it's the system default and working on the registration form.

**Comment by sebastienlapoux** [comment]
Thanks @conconnl.

The registration form https://showcase.joomla.org/register has always an anti-spam system. Which is working well and avoid bad account creation since years ago.
If any issue appear it will make sense to use another system, but not currently.

**Comment by conconnl** [comment]
Ok, for now!
