### ISSUE TITLE
Upgrade site template

### ISSUE THREAD

**Issue by conconnl** [joomla/showcase.joomla.org#20]
@sebastienlapoux please work on updating the site to the latest template.
This will fix certain usability issues, but mainly clean unneeded things.

**Comment by conconnl** [comment]
@sebastienlapoux & @alexandrelapoux 
Were you able to work on this?
Do you need any guidance?

**Comment by sebastienlapoux** [comment]
Hi @conconnl ,

Yes, sorry I missed this ticket but it has been done on September 20 2021 like mentioned in our discussion on Ring.

Template 3.1.0

Regards.
