### ISSUE TITLE
Error After Moderating Sites

### ISSUE THREAD

**Issue by aboarken** [joomla/showcase.joomla.org#21]
I am getting an "error" message as shown below after I successfully moderate sites in Showcase Directory Directory site.

![Error After Moderation](https://user-images.githubusercontent.com/18500882/134779042-40ea8923-42e3-425f-b942-de64d1815585.png)

**Comment by sebastienlapoux** [comment]
Thanks @aboarken . Maybe due to Template update.

**Comment by aboarken** [comment]
> Thanks @aboarken . Maybe due to Template update.

I think there is a redirection issue since the moderation is successfully completed but its not redirecting back to Showcase Administration. Most Welcome @sebastienlapoux

**Comment by aboarken** [comment]
@sebastienheraud I have moderated a site today and no error came up.

**Comment by sebastienheraud** [comment]
Hi @aboarken,

Thanks for the feedback. I had a try on a DEV environment earlier today and was not able to replicate the issue (but I only did one test).
I was thinking maybe it depends on which button is clicked.
I tried with "Save & Close" and it was all good, but can it be an issue only with "Save & Next" ? No sure which one you use.

Or it may depend on which checkboxes/fields/status are changed before saving.

Thanks,
Sebastien

**Comment by aboarken** [comment]
@sebastienheraud Thank you for your reply. Actually I have clicked on "Save and Close" and then an error was thrown knowing that I have checked all boxes. Today, I have moderated another site which requires some changes from the user and also I have clicked on "Save and Next" but everything was great. Do you think it was a caching issue? You know better than me. Waiting for your reply.

**Comment by sebastienheraud** [comment]
Hi @aboarken,

Not really sure what happened then, but it looks like its working so let's close this issue for now.

Sebastien
