### ISSUE TITLE
Error Uploading Image

### ISSUE THREAD

**Issue by aboarken** [joomla/showcase.joomla.org#22]
I have noticed that I am not able to upload an image to a submission since the submitter didn't upload it (Knowing that uploading an image to the submission is mandatory). Also I have noticed zero submissions to the Showcase Directory since that submission. Attached a screenshot of the error while uploading the image:

![Upload Error](https://user-images.githubusercontent.com/18500882/187706000-2f1ea5d9-c965-4691-a3b1-0520a3b92993.png)

**Comment by aboarken** [comment]
@sebastienheraud Please can you check it. Thank you.

**Comment by sebastienlapoux** [comment]
Hi @aboarken,

Thank you! Always the same, not enough space, due to Akeeba local backup.

![image](https://user-images.githubusercontent.com/13470265/187737476-8ce09618-fabb-4039-87ad-4379270cf2c9.png)

Please try again.

Regards

**Comment by aboarken** [comment]
Thanks @sebastienlapoux , its working now. We can configure Akeeba Backups to a new destination (Google Drive) as long as we have storage on Google Drive. If you need help I am ready.

**Comment by sebastienlapoux** [comment]
Thanks @aboarken. Already done on S3. Concerns just some specific backup. Would be great to have just more space...
