### ISSUE TITLE
[Implement] - JCE Pro

### ISSUE THREAD

**Issue by conconnl** [joomla/showcase.joomla.org#3]
Please implement JCE Pro, which is our default editor for J! Sites.

**Comment by sebastienlapoux** [comment]
Thanks @conconnl .

Like you know, the showcase site is using TinyMCE, the official Joomla Editor. Standard is good, not when the standard is not real standard and require to waste time on it.
This change will bring nothing to the site or to the update process and we will face certainly lot of small fix to do about design.

**Comment by conconnl** [comment]
Let's keep it like this for now.
We will see what any future standard will bring
