### ISSUE TITLE
Log folder is not on default location

### ISSUE THREAD

**Issue by conconnl** [joomla/showcase.joomla.org#4]
Please correct the "Path to Log Folder" setting to the Joomla default location

**Comment by sebastienlapoux** [comment]
Thanks @conconnl !

The current path to log folder is "/home/showcase/public_html/logs". Please let us know what the "Joomla default location". Do you means about j.org websites?

Thanks.

**Comment by conconnl** [comment]
The default in J! CMS not our website specifically is in the administrator folder. 
This has been changed a long time ago by the core team. This is also where audit tools check on. That is why I created the issue, I saw the old location

**Comment by sebastienlapoux** [comment]
Thanks. First time we heard about this. We don't know this folder. We will try to find the new folder into the "guideline".

**Comment by conconnl** [comment]
It’s not in our guideline. 
It’s the default when you install a new joomla website.
It’s in the code of the CMS itself. 
See: https://github.com/joomla/joomla-cms/blob/staging/installation/configuration.php-dist

**Comment by sebastienlapoux** [comment]
Seems not to be very old. Thanks a lot @conconnl . Done!

**Comment by conconnl** [comment]
Thanks
