### ISSUE TITLE
J! Template folder holds a lot of templates

### ISSUE THREAD

**Issue by conconnl** [joomla/showcase.joomla.org#5]
Please check all templates in the "/templates/" folder.
There seems to be more J! templates then in the CMS itself.
It also holds a lot of special templates, if these are required, please add them to GitHub

**Comment by sebastienlapoux** [comment]
Thanks @conconnl .

SEBLOD extension is using templates. These templates are centralized into Joomla template component. Example Seb_accordion template is used on FAQ page https://showcase.joomla.org/about-jsd/faqs.html.
Only seb_globe is unused. It was to display site items on js global earth that you can move is 3D. We will delete it if the team decide to not use this view.

**Comment by conconnl** [comment]
My message had to parts.
1. I holds multiple J templates. (Joomla_2 etc), also many Seblod templates. 
2. All what is custom needs to be in GitHub, so that would mean as all those templates Seblod and others are required, we need to make sure the are registered.

**Comment by sebastienlapoux** [comment]
Thanks @conconnl .
In progress

**Comment by conconnl** [comment]
How is it going?

**Comment by sebastienlapoux** [comment]
Hi @conconnl ,

"Joomla" template is used as the standard main template.

The 11 other templates are SEBLOD templates used by the showcase site. These templates are mainly templates included into SEBLOD core or available on seblod.com into Extensions Store. 4 templates below have been created for the showcase site and are "custom"
Seb_bootstrap_carousel 
Seb_bootstrap_carousel_flex 
Seb_bootstrap_carousel_split
Seb_owl_carousel

There are into /templates. 

Could you please push them on GitHub?  Maybe it makes more sense to push the full showcase website on GitHub.
Please confirm that it will not be public but accessible to webmaster team or other specific group that you know more than me?

Thank you!

**Comment by conconnl** [comment]
This is a public repository, so having the whole website in it, requires some more work.
I don't see why custom templates shouldn't be there....
I don't mind uploading them for you, you also have access yourself.

**Comment by sebastienlapoux** [comment]
-> I don't see why custom templates shouldn't be there....

Maybe the author of the code doesn't wish to share publicly the code for a ton of reasons. Do you say that any custom code or not public code used by a joomla.org website must be public?

**Comment by conconnl** [comment]
Yes and No, it depends on various things.
We will look at it in the future.
