### ISSUE TITLE
Github access

### ISSUE THREAD

**Issue by sebastienlapoux** [joomla/showcase.joomla.org#9]
@conconnl  Sebastien Heraud, Lionel Ratel, Alexandre Lapoux from Octopoos team are working on showcase site too. How please give them an access on the Github showcase.joomla.org rep?
Thanks!

**Comment by HLeithner** [comment]
Which access do they need beside making pull requests?

**Comment by conconnl** [comment]
An invite will be send to all members.
When accepted I will add them to the Showcase Team

**Comment by sebastienlapoux** [comment]
Thanks a lot!

**Comment by conconnl** [comment]
I will keep it open for reference.
The have been invited, but I can only really add them to the team, after they accepted

**Comment by conconnl** [comment]
Lionel didn't accept request yet.
When he has done that, he can let us know and we will add him.

**Comment by sebastienlapoux** [comment]
Thanks @conconnl! Lionel approved the request some minutes ago.
